AllCops:
  TargetRubyVersion: 1.9

Style/StringLiterals:
  EnforcedStyle: single_quotes

AllCops:
  Exclude:
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'config/initializers/secret_token.rb'

Metrics/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false
