version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f /app/tmp/pids/server.pid && rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    depends_on:
      - db
      - redis
      - sidekiq
    env_file:
      - .env
    stdin_open: true
    tty: true

  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  redis:
    image: redis:3.2
    container_name: redis
    ports:
      - "6380:6379"

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  pg_data:
