version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f /app/tmp/pids/server.pid && rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_USER: appuser
      DATABASE_PASSWORD: password
      DATABASE_NAME: appdb
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://appuser:password@db:5432/ecommerce_puntospoint_development
    stdin_open: true
    tty: true

  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  redis:
    image: redis:3.2
    container_name: redis
    ports:
      - "6380:6379"

  resque_web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails server -b 0.0.0.0 -p 3001
    ports:
      - "3001:3001"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
      - db
      - resque_worker

  resque_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rake resque:work QUEUE=* --trace
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://appuser:password@db:5432/ecommerce_puntospoint_development
      DATABASE_HOST: db
      DATABASE_USER: appuser
      DATABASE_PASSWORD: password
      DATABASE_NAME: appdb
    depends_on:
      - redis
      - db
    volumes:
      - .:/app

volumes:
  pg_data:
