default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  # database: <%= ENV['DATABASE_NAME'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce_puntospoint_development

test:
  <<: *default
  database: ecommerce_puntospoint_test

production:
  <<: *default
  database: ecommerce_puntospoint_production
  username: ecommerce_puntospoint
  password: <%= ENV['ECOMMERCE_PUNTOSPOINT_DATABASE_PASSWORD'] %>
